/**
 * v0.6.3 I7 — JS verifies fixtures written by the Python SDK.
 *
 * Mirror of cloakllm-py/tests/test_cross_sdk_round_trip.py: each SDK's
 * test suite verifies the OTHER SDK's fixtures so a divergence in
 * canonical JSON / audit hash chaining / Ed25519 signing breaks CI on
 * both sides immediately.
 *
 * To regenerate fixtures (commit the result):
 *     node test/fixtures/generate_cross_sdk_fixtures.js
 *     python ../cloakllm-py/tests/fixtures/generate_cross_sdk_fixtures.py
 */

'use strict';

const { describe, it } = require('node:test');
const assert = require('node:assert/strict');
const fs = require('fs');
const path = require('path');
const os = require('os');

const { Shield, ShieldConfig } = require('../src');
const { SanitizationCertificate } = require('../src/attestation');

const HERE = __dirname;
const FIXTURES = path.join(HERE, 'fixtures');

function fixturePath(name) {
  return path.join(FIXTURES, name);
}

function loadMetadata() {
  return JSON.parse(fs.readFileSync(fixturePath('cross_sdk_metadata.json'), 'utf-8'));
}

function tmpDir() {
  return fs.mkdtempSync(path.join(os.tmpdir(), 'cloakllm-i7-js-vs-py-'));
}

function fixtureExists(name) {
  return fs.existsSync(fixturePath(name));
}

// ─── JS verifies Python audit chain ───────────────────────────────────────

describe('I7 — JS verifies the Python-written audit chain', () => {
  it('Python chain passes JS verifyChain', () => {
    if (!fixtureExists('audit_chain_py.jsonl')) {
      // CI race — fixture generated by the python repo's pre-step
      console.warn('skip: audit_chain_py.jsonl not present');
      return;
    }
    const dir = tmpDir();
    try {
      fs.copyFileSync(
        fixturePath('audit_chain_py.jsonl'),
        path.join(dir, 'audit_2026-04-19.jsonl'),
      );
      const shield = new Shield(new ShieldConfig({ logDir: dir, auditEnabled: false }));
      const { valid, errors } = shield.audit.verifyChain();
      assert.ok(
        valid,
        `Python-written chain failed JS verifyChain. ` +
        `Errors: ${JSON.stringify(errors)}`,
      );
    } finally {
      fs.rmSync(dir, { recursive: true, force: true });
    }
  });

  it('Python chain fixture has the entry count its metadata records', () => {
    if (!fixtureExists('audit_chain_py.jsonl')) return;
    const meta = loadMetadata();
    const pyMeta = meta.python_chain || {};
    assert.equal(pyMeta.chain_valid, true, 'python generator reported chain invalid');
    const content = fs.readFileSync(fixturePath('audit_chain_py.jsonl'), 'utf-8');
    const actual = content.split('\n').filter(l => l.trim()).length;
    assert.equal(actual, pyMeta.entries);
  });
});

// ─── JS verifies Python certificate ───────────────────────────────────────

describe('I7 — JS verifies the Python-signed certificate', () => {
  it('Python certificate signature verifies in JS', () => {
    if (!fixtureExists('certificate_py.json')) {
      console.warn('skip: certificate_py.json not present');
      return;
    }
    const wrapper = JSON.parse(fs.readFileSync(fixturePath('certificate_py.json'), 'utf-8'));
    const certDict = wrapper.certificate;
    const publicKey = Buffer.from(wrapper.public_key_b64, 'base64');
    const cert = SanitizationCertificate.fromDict(certDict);
    assert.ok(
      cert.verify(publicKey),
      'Python-signed certificate failed JS verify(). ' +
      'Either canonical JSON or the Ed25519 signing scheme diverged between SDKs.',
    );
  });

  it('Python certificate fields match its metadata snapshot', () => {
    if (!fixtureExists('certificate_py.json')) return;
    const meta = loadMetadata();
    const pyMeta = meta.python_certificate || {};
    const wrapper = JSON.parse(fs.readFileSync(fixturePath('certificate_py.json'), 'utf-8'));
    const cert = wrapper.certificate;
    assert.equal(cert.entity_count, pyMeta.entity_count);
    assert.equal(cert.input_hash, pyMeta.input_hash);
    assert.equal(cert.output_hash, pyMeta.output_hash);
  });
});

// ─── JS verifies its own fixtures (sanity guard) ──────────────────────────

describe('I7 — JS-written fixtures still verify in JS', () => {
  it('JS chain self-verifies', () => {
    if (!fixtureExists('audit_chain_js.jsonl')) return;
    const dir = tmpDir();
    try {
      fs.copyFileSync(
        fixturePath('audit_chain_js.jsonl'),
        path.join(dir, 'audit_2026-04-19.jsonl'),
      );
      const shield = new Shield(new ShieldConfig({ logDir: dir, auditEnabled: false }));
      const { valid, errors } = shield.audit.verifyChain();
      assert.ok(valid, `JS self-chain failed: ${JSON.stringify(errors)}`);
    } finally {
      fs.rmSync(dir, { recursive: true, force: true });
    }
  });

  it('JS certificate self-verifies', () => {
    if (!fixtureExists('certificate_js.json')) return;
    const wrapper = JSON.parse(fs.readFileSync(fixturePath('certificate_js.json'), 'utf-8'));
    const cert = SanitizationCertificate.fromDict(wrapper.certificate);
    const publicKey = Buffer.from(wrapper.public_key_b64, 'base64');
    assert.ok(cert.verify(publicKey));
  });
});
